import type { Metadata } from 'next';
import Script from 'next/script';
import './globals.css';
import './streak-tuning.css';

export const metadata: Metadata = {title:'BeatForge',description:'5 lane web rhythm game prototype'};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
 return <html lang="en"><body>{children}
 <Script id="beatforge-fullscreen" strategy="afterInteractive">{`
 (()=>{let shell=null,moved=[],observer=null;const move=(el,target)=>{if(!el||moved.some(x=>x.el===el))return;moved.push({el,parent:el.parentNode,next:el.nextSibling});target.appendChild(el)};const moveModal=()=>{if(!shell)return;document.querySelectorAll('body > .resultBackdrop, body > main > .resultBackdrop').forEach(el=>move(el,shell))};const size=()=>{if(!shell)return;const center=shell.querySelector('.beatforgeFullscreenCenter'),controls=shell.querySelector('.controls');if(!center)return;const scale=Math.max(1,Math.min(1.35,(innerWidth-608)/920,(innerHeight-105)/610));center.style.width=920*scale+'px';center.style.height=610*scale+'px';center.style.setProperty('--bf-scale',String(scale));if(controls)controls.style.width=920*scale+'px'};const restore=()=>{observer?.disconnect();observer=null;removeEventListener('resize',size);[...moved].reverse().forEach(({el,parent,next})=>parent?.insertBefore(el,next));moved=[];shell?.remove();shell=null};const enter=async()=>{const game=document.querySelector('.game'),controls=document.querySelector('.controls');if(!game||!controls)return;const global=document.querySelector('.leaderGlobal'),friends=document.querySelector('.leaderFriends');shell=document.createElement('div');shell.className='beatforgeFullscreenShell';const arena=document.createElement('div');arena.className='beatforgeFullscreenArena';const left=document.createElement('div'),center=document.createElement('div'),right=document.createElement('div');left.className='beatforgeFullscreenSide left';center.className='beatforgeFullscreenCenter';right.className='beatforgeFullscreenSide right';arena.append(left,center,right);shell.appendChild(arena);document.body.appendChild(shell);move(global,left);move(game,center);move(friends,right);move(controls,shell);size();addEventListener('resize',size);observer=new MutationObserver(moveModal);observer.observe(document.body,{childList:true,subtree:true});try{await shell.requestFullscreen();size();moveModal()}catch{restore()}};const toggle=async()=>document.fullscreenElement?document.exitFullscreen():enter();document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&shell)restore();else if(shell)size()});const install=()=>{const controls=document.querySelector('.controls');if(!controls||controls.querySelector('.fullscreenBtn'))return;const b=document.createElement('button');b.className='secondary fullscreenBtn';b.textContent='FULLSCREEN';b.onclick=toggle;controls.insertBefore(b,controls.querySelector('.volume')||null)};new MutationObserver(install).observe(document.body,{childList:true,subtree:true});install()})();
 `}</Script>
 <Script id="beatforge-star-system" strategy="afterInteractive">{`
 (()=>{let lastStars=0,finalStars=0,lastRaw=-1;const update=()=>{const meter=document.querySelector('.starMeter'),rail=meter?.querySelector('.starRail i'),stars=[...(meter?.querySelectorAll('.stars span')||[])];if(!meter||!rail||!stars.length)return;const raw=parseFloat(rail.style.width)||0;if(raw===lastRaw)return;lastRaw=raw;const progress=Math.max(0,Math.min(5,raw/20)),earned=Math.min(5,Math.floor(progress+.0001)),fraction=earned>=5?1:progress-earned;rail.style.setProperty('--bf-star-progress',fraction*100+'%');if(earned>lastStars){finalStars=earned;const star=stars[earned-1];star?.classList.remove('starEarnPop');void star?.offsetWidth;star?.classList.add('starEarnPop');meter.classList.remove('starMeterBurst');void meter.offsetWidth;meter.classList.add('starMeterBurst');const game=document.querySelector('.game');if(game){game.classList.remove('starGameFlash');void game.offsetWidth;game.classList.add('starGameFlash')}}if(earned<lastStars)finalStars=earned;lastStars=earned};const add=()=>{document.querySelectorAll('.resultCard').forEach(card=>{if(card.querySelector('.resultStarsFinal'))return;const label=card.querySelector('.scoreLabel');if(!label||!card.textContent?.includes('SONG COMPLETE'))return;const wrap=document.createElement('div');wrap.className='resultStarsFinal';wrap.innerHTML='<span>STAR RATING</span><div class="resultStarsRow">'+[1,2,3,4,5].map(i=>'<b class="'+(i<=finalStars?'earned':'')+'">★</b>').join('')+'</div>';label.insertAdjacentElement('afterend',wrap)})};new MutationObserver(m=>{if(m.some(x=>x.type==='childList'))add()}).observe(document.body,{subtree:true,childList:true});setInterval(update,80)})();
 `}</Script>
 <Script id="beatforge-personal-best" strategy="afterInteractive">{`
 (()=>{const keyFor=()=>{const g=document.querySelector('.game');const title=document.querySelector('.leaderGlobal .leaderHead strong')?.textContent?.trim()||'demo';const diff=document.querySelector('.leaderGlobal .leaderHead small')?.textContent?.split('·')[0]?.trim()||'unknown';return 'beatforge-pb:'+title.toLowerCase()+':'+diff.toLowerCase()+':'+(g?.querySelectorAll('.lane').length||5)};const num=t=>Number((t||'').replace(/[^0-9.]/g,''))||0;const enhance=()=>{document.querySelectorAll('.resultCard').forEach(card=>{if(!card.textContent?.includes('SONG COMPLETE')||card.querySelector('.personalBestResult'))return;const score=num(card.querySelector('.finalScore')?.textContent),meta=card.querySelectorAll('.resultMeta>div'),accuracy=num(meta[0]?.querySelector('b')?.textContent),combo=num(meta[1]?.querySelector('b')?.textContent),key=keyFor();let old=null;try{old=JSON.parse(localStorage.getItem(key)||'null')}catch{}const first=!old;const isPB=!old||score>Number(old.score||0);const best={score:Math.max(score,Number(old?.score||0)),accuracy:Math.max(accuracy,Number(old?.accuracy||0)),combo:Math.max(combo,Number(old?.combo||0))};try{localStorage.setItem(key,JSON.stringify(best))}catch{}const box=document.createElement('div');box.className='personalBestResult '+(isPB?'newPB':'');if(first)box.innerHTML='<strong>FIRST SCORE SAVED</strong><span>This is now your personal best.</span>';else if(isPB){const gain=score-Number(old.score||0);box.innerHTML='<strong>NEW PERSONAL BEST!</strong><span>+'+gain.toLocaleString()+' SCORE</span><small>Accuracy '+Number(old.accuracy||0).toFixed(1)+'% → '+accuracy.toFixed(1)+'% · Max combo '+Number(old.combo||0)+' → '+combo+'</small>'}else{const gap=Math.max(0,Number(old.score||0)-score);box.innerHTML='<strong>PERSONAL BEST '+Number(old.score||0).toLocaleString()+'</strong><span>'+gap.toLocaleString()+' from your best</span><small>Best accuracy '+Number(old.accuracy||0).toFixed(1)+'% · Best combo '+Number(old.combo||0)+'</small>'}const actions=card.querySelector('.resultActions');actions?.insertAdjacentElement('beforebegin',box)})};new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});enhance()})();
 `}</Script>
 <style>{`
 .beatforgeFullscreenShell{background:#070a10;width:100vw;height:100vh;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px;overflow:hidden;padding:8px 16px;box-sizing:border-box}.beatforgeFullscreenArena{width:100%;display:grid;grid-template-columns:280px auto 280px;gap:24px;align-items:center;justify-content:center;min-height:0}.beatforgeFullscreenCenter{position:relative;min-width:920px;min-height:610px;overflow:visible;flex:none}.beatforgeFullscreenCenter>.game{position:absolute!important;left:50%!important;top:50%!important;width:920px!important;height:610px!important;min-height:610px!important;max-height:610px!important;margin:0!important;transform:translate(-50%,-50%) scale(var(--bf-scale,1))!important;transform-origin:center center!important}.beatforgeFullscreenSide{width:280px;min-width:280px;overflow:visible}.beatforgeFullscreenSide>.leaderSide{position:static!important;inset:auto!important;transform:none!important;width:280px!important;min-width:280px!important;max-width:280px!important;max-height:610px!important;margin:0!important;display:block!important;visibility:visible!important;overflow:hidden!important;box-sizing:border-box!important}.beatforgeFullscreenSide .leaderboard,.beatforgeFullscreenSide .leaderRow{max-width:100%!important;min-width:0!important;box-sizing:border-box!important;overflow:hidden!important}.beatforgeFullscreenSide .leaderRow{grid-template-columns:auto minmax(0,1fr) auto!important}.beatforgeFullscreenSide .leaderRow strong{min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}.beatforgeFullscreenShell>.controls{max-width:calc(100vw - 32px);margin:0!important;display:flex!important;visibility:visible!important;flex:0 0 auto}.beatforgeFullscreenShell>.resultBackdrop{position:fixed!important;inset:0!important;z-index:9999!important;width:100%!important;height:100%!important}@media(max-width:1500px){.beatforgeFullscreenArena{grid-template-columns:240px auto 240px;gap:14px}.beatforgeFullscreenSide,.beatforgeFullscreenSide>.leaderSide{width:240px!important;min-width:240px!important;max-width:240px!important}}
 .leaderRow.youLive{outline:none!important;box-shadow:inset 0 0 0 1px rgba(255,255,255,.22)!important}.starMeter{position:relative;padding:11px 12px!important}.stars{font-size:20px!important;gap:4px}.starRail{height:7px!important;margin-top:9px!important;background:#252b38!important;border:1px solid #3a4253;overflow:hidden!important}.starRail i{height:100%!important;width:var(--bf-star-progress,0%)!important;background:linear-gradient(90deg,#f6b93b,#ffd54a,#fff0a0)!important;box-shadow:0 0 10px #ffd54a88;transition:width .12s linear!important}.starMeter:after{content:none!important;display:none!important}.starEarnPop{animation:bfStarPop .7s cubic-bezier(.2,.9,.25,1.25)!important}.starMeterBurst{animation:bfMeterBurst .65s ease-out}.starGameFlash:after{content:'';position:absolute;inset:0;z-index:20;pointer-events:none;border:2px solid #ffd54a88;border-radius:18px;animation:bfGameStarFlash .65s ease-out forwards}@keyframes bfStarPop{0%{transform:scale(.6)}35%{transform:scale(1.65) rotate(10deg);filter:brightness(1.8);text-shadow:0 0 24px #ffd54a}100%{transform:scale(1)}}@keyframes bfMeterBurst{35%{box-shadow:0 0 24px #ffd54a66;border-color:#ffd54aaa}}@keyframes bfGameStarFlash{0%{opacity:0}30%{opacity:1;box-shadow:inset 0 0 45px #ffd54a20}100%{opacity:0}}.resultStarsFinal{margin:14px auto 2px;padding:12px 16px;border:1px solid #343a49;border-radius:12px;background:#181c26;width:max-content;min-width:210px}.resultStarsFinal>span{display:block;color:#8e95a5;font-size:9px;font-weight:900;letter-spacing:1.4px;margin-bottom:6px}.resultStarsRow{display:flex;justify-content:center;gap:8px;font-size:26px;color:#343a48}.resultStarsRow b{font-weight:400}.resultStarsRow b.earned{color:#ffd54a;text-shadow:0 0 12px #ffd54a88}
 .personalBestResult{margin:14px 0;padding:13px 16px;border:1px solid #343a49;border-radius:12px;background:#11151f;text-align:center;display:grid;gap:4px}.personalBestResult strong{font-size:13px;letter-spacing:.08em}.personalBestResult span{font-size:18px;font-weight:900}.personalBestResult small{color:#9aa2b4;font-size:10px}.personalBestResult.newPB{border-color:#ffd54a88;background:linear-gradient(135deg,#1a1720,#211b0d);box-shadow:0 0 24px #ffd54a18}.personalBestResult.newPB strong,.personalBestResult.newPB span{color:#ffd54a}.personalBestResult.newPB{animation:bfPbPop .55s ease-out}@keyframes bfPbPop{0%{transform:scale(.96);opacity:.2}55%{transform:scale(1.025)}100%{transform:scale(1);opacity:1}}
 `}</style>
 </body></html>;
}
