'use client';
import {ChangeEvent,useEffect,useRef,useState} from 'react';
type Note={id:number,time:number,lane:number,duration?:number,hit?:boolean,miss?:boolean,holding?:boolean,completed?:boolean};
type Feedback='READY'|'PERFECT'|'GREAT'|'GOOD'|'MISS';
type Instrument='Vocals'|'Drums'|'Bass'|'Melody';
type Difficulty='Easy'|'Medium'|'Hard'|'Expert';
type StemCache=Record<Instrument,Note[]>;
const defaults=['d','f','j','k','l'];
const comboMultiplier=(combo:number)=>combo>=50?5:combo>=30?4:combo>=20?3:combo>=10?2:1;
const demo:Note[]=Array.from({length:72},(_,i)=>({id:i,time:2+i*.42,lane:(i*3+i%2)%5}));
export default function Home(){
 const [laneCount,setLaneCount]=useState(5),[instrument,setInstrument]=useState<Instrument>('Vocals'),[difficulty,setDifficulty]=useState<Difficulty>('Medium'),[baseNotes,setBaseNotes]=useState<Note[]>(demo),[keys,setKeys]=useState(defaults),[notes,setNotes]=useState<Note[]>(demo),[running,setRunning]=useState(false),[time,setTime]=useState(0),[combo,setCombo]=useState(0),[score,setScore]=useState(0),[judge,setJudge]=useState<Feedback>('READY'),[pressed,setPressed]=useState<number|null>(null),[impact,setImpact]=useState<{lane:number,id:number,kind:Feedback}|null>(null),[songName,setSongName]=useState('Demo chart'),[audioUrl,setAudioUrl]=useState<string|null>(null),[analyzing,setAnalyzing]=useState(false),[status,setStatus]=useState('Upload a song, or play the demo.'),[duration,setDuration]=useState(34),[volume,setVolume]=useState(0.8),[resultsOpen,setResultsOpen]=useState(false),[backendMode,setBackendMode]=useState<'AI'|'LOCAL'>('LOCAL'),[heldLanes,setHeldLanes]=useState<boolean[]>(Array(5).fill(false)),[hitStats,setHitStats]=useState({perfect:0,great:0,good:0,miss:0,maxCombo:0,timingSum:0,timingHits:0}),[stemCache,setStemCache]=useState<StemCache|null>(null),[holdScore,setHoldScore]=useState(0);
 const audio=useRef<HTMLAudioElement|null>(null),raf=useRef(0),start=useRef(0),timeRef=useRef(0),impactId=useRef(0),urlRef=useRef<string|null>(null),fileRef=useRef<File|null>(null),progressKnob=useRef<HTMLDivElement|null>(null),progressFill=useRef<HTMLDivElement|null>(null),remainingLabel=useRef<HTMLSpanElement|null>(null),heldLanesRef=useRef<boolean[]>(Array(5).fill(false)),comboRef=useRef(0),lastFrameRef=useRef<number|null>(null),holdRemainder=useRef(0);
 const buildChart=(source:Note[],lanes:number,diff:Difficulty)=>{const keep={Easy:.38,Medium:.62,Hard:.82,Expert:1}[diff];const kept=source.filter((_,i)=>keep===1||((i*37)%100)/100<keep);const blocked=Array(lanes).fill(-Infinity);return kept.map((n,i)=>{const preferred=n.lane%lanes;const order=[preferred,...Array.from({length:lanes},(_,x)=>x).filter(x=>x!==preferred)];const lane=order.find(x=>blocked[x]<=n.time-.08)??preferred;const dur=n.duration||0;if(dur>=.45)blocked[lane]=n.time+dur;return {...n,id:i,lane,hit:false,miss:false,holding:false,completed:false}})};
 useEffect(()=>{setKeys(k=>{const presets=[['f','j','k'],['d','f','j','k'],['d','f','j','k','l']][laneCount-3];return presets.map((d,i)=>k[i]??d)});setNotes(buildChart(baseNotes,laneCount,difficulty));setStatus(s=>songName==='Demo chart'?s:`${buildChart(baseNotes,laneCount,difficulty).length} notes · ${instrument} · ${difficulty} · ${laneCount} lanes`);},[laneCount,difficulty]);
 const resetNotes=()=>setNotes(n=>n.map(x=>({...x,hit:false,miss:false,holding:false,completed:false}))); 
 useEffect(()=>{heldLanesRef.current=heldLanes},[heldLanes]);
 useEffect(()=>{comboRef.current=combo},[combo]);
 const resetStats=()=>setHitStats({perfect:0,great:0,good:0,miss:0,maxCombo:0,timingSum:0,timingHits:0});
 const finishSong=()=>{setRunning(false);cancelAnimationFrame(raf.current);setResultsOpen(true)};
 const stop=()=>{setRunning(false);cancelAnimationFrame(raf.current);if(audio.current){audio.current.pause();audio.current.currentTime=0}setTime(0);timeRef.current=0;setCombo(0);comboRef.current=0;setScore(0);setHoldScore(0);holdRemainder.current=0;lastFrameRef.current=null;setJudge('READY');setPressed(null);setResultsOpen(false);resetStats();resetNotes()};
 const play=async()=>{setResultsOpen(false);resetStats();setCombo(0);comboRef.current=0;setScore(0);setHoldScore(0);holdRemainder.current=0;lastFrameRef.current=null;setJudge('READY');setPressed(null);resetNotes();setTime(0);timeRef.current=0;if(audio.current&&audioUrl){audio.current.currentTime=0;try{await audio.current.play()}catch{return}start.current=performance.now()/1000-audio.current.currentTime}else start.current=performance.now()/1000;setRunning(true)};
 useEffect(()=>{if(!running)return;let lastUiUpdate=0;const loop=()=>{const now=performance.now()/1000;const dt=lastFrameRef.current==null?0:Math.min(.05,Math.max(0,now-lastFrameRef.current));lastFrameRef.current=now;const t=audio.current&&audioUrl?audio.current.currentTime:now-start.current;timeRef.current=t;const total=audio.current&&audioUrl&&Number.isFinite(audio.current.duration)&&audio.current.duration>0?audio.current.duration:(audioUrl?duration:34);const smoothT=audio.current&&audioUrl&&!audio.current.paused?Math.min(total,t+Math.max(0,now-(start.current+t))):t;const p=total?Math.max(0,Math.min(1,smoothT/total)):0;if(progressFill.current)progressFill.current.style.height=`${p*100}%`;if(progressKnob.current)progressKnob.current.style.bottom=`calc(${p*100}% - 8px)`;if(remainingLabel.current)remainingLabel.current.textContent=fmt(Math.max(0,total-smoothT));timeRef.current=smoothT;setTime(smoothT);setNotes(old=>{let missedCount=0;let holdBonus=0;let changed=false;const next=old.map(n=>{if(!n.hit&&!n.miss&&smoothT-n.time>.16){missedCount++;changed=true;return{...n,miss:true}}if(n.holding&&!n.miss){const end=n.time+(n.duration||0);if(heldLanesRef.current[n.lane]&&smoothT<end){holdBonus+=dt*250*comboMultiplier(comboRef.current)}if(smoothT>=end){changed=true;return{...n,holding:false,completed:true}}}return n});if(holdBonus){holdRemainder.current+=holdBonus;const pts=Math.floor(holdRemainder.current);if(pts>0){holdRemainder.current-=pts;setScore(s=>s+pts);setHoldScore(s=>s+pts)}}if(missedCount){setCombo(0);comboRef.current=0;setJudge('MISS');setHitStats(s=>({...s,miss:s.miss+missedCount}))}return changed?next:old});if(audio.current&&audioUrl&&audio.current.ended)finishSong();else if(!audioUrl&&t>34)finishSong();else raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf.current)},[running,audioUrl,duration]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{if(e.repeat)return;const lane=keys.indexOf(e.key.toLowerCase());if(lane<0)return;e.preventDefault();setHeldLanes(h=>h.map((v,i)=>i===lane?true:v));heldLanesRef.current=heldLanesRef.current.map((v,i)=>i===lane?true:v);setPressed(lane);if(!running)return;const now=timeRef.current;setNotes(old=>{let best=-1,delta=99;old.forEach((n,i)=>{const d=Math.abs(n.time-now);if(n.lane===lane&&!n.hit&&!n.miss&&d<delta){best=i;delta=d}});let kind:Feedback='MISS';if(best<0||delta>.16){setCombo(0);comboRef.current=0;setJudge('MISS');setHitStats(s=>({...s,miss:s.miss+1}))}else{const copy=[...old];const target=copy[best];const signedDelta=now-target.time;const isHold=(target.duration||0)>=.45;let basePoints=500;copy[best]={...target,hit:true,holding:isHold,completed:!isHold};if(delta<=.05){kind='PERFECT';basePoints=1000;setHitStats(s=>({...s,perfect:s.perfect+1,timingSum:s.timingSum+signedDelta,timingHits:s.timingHits+1}))}else if(delta<=.10){kind='GREAT';basePoints=800;setHitStats(s=>({...s,great:s.great+1,timingSum:s.timingSum+signedDelta,timingHits:s.timingHits+1}))}else{kind='GOOD';basePoints=500;setHitStats(s=>({...s,good:s.good+1,timingSum:s.timingSum+signedDelta,timingHits:s.timingHits+1}))}setJudge(kind);setCombo(c=>{const next=c+1;comboRef.current=next;setScore(s=>s+basePoints*comboMultiplier(next));setHitStats(s=>({...s,maxCombo:Math.max(s.maxCombo,next)}));return next});impactId.current++;setImpact({lane,id:impactId.current,kind});return copy}impactId.current++;setImpact({lane,id:impactId.current,kind});return old})};
 const up=(e:KeyboardEvent)=>{const lane=keys.indexOf(e.key.toLowerCase());if(lane<0)return;setHeldLanes(h=>h.map((v,i)=>i===lane?false:v));heldLanesRef.current=heldLanesRef.current.map((v,i)=>i===lane?false:v);setPressed(p=>p===lane?null:p);if(!running)return;setNotes(old=>old.map(n=>n.lane===lane&&n.holding&&!n.miss?{...n,holding:false,completed:true}:n))};
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up)}},[keys,running]);
 const analyze=(buffer:AudioBuffer)=>{const data=buffer.getChannelData(0),sr=buffer.sampleRate,hop=1024,win=2048;const energy:number[]=[];for(let p=0;p+win<data.length;p+=hop){let sum=0;for(let j=0;j<win;j+=4){const v=data[p+j];sum+=v*v}energy.push(sum/(win/4))}const novelty=energy.map((v,i)=>i?Math.max(0,v-energy[i-1]):0);const sorted=[...novelty].sort((a,b)=>a-b);const threshold=sorted[Math.floor(sorted.length*.82)]||0;const out:Note[]=[];let last=-1;for(let i=2;i<novelty.length-2;i++){const t=i*hop/sr;if(t<.8||t-last<.18)continue;const v=novelty[i];if(v>threshold&&v>=novelty[i-1]&&v>=novelty[i+1]){const lane=(Math.floor((energy[i]*1e7))+i*7)%5;out.push({id:out.length,time:t,lane});last=t;if(out.length>=1200)break}}return out.length>8?out:Array.from({length:Math.max(12,Math.floor(buffer.duration*2))},(_,i)=>({id:i,time:1+i*.5,lane:i%5}))};
 const ding=()=>{try{const ctx=new AudioContext();const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=880;g.gain.setValueAtTime(.16,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.22);o.connect(g);g.connect(ctx.destination);o.start();o.stop(ctx.currentTime+.22);o.onended=()=>ctx.close()}catch{}};
 const loadCachedStem=(selected:Instrument,cache:StemCache|null=stemCache)=>{if(!cache)return;const generated=cache[selected];setBaseNotes(generated);const chart=buildChart(generated,laneCount,difficulty);setNotes(chart);setBackendMode('AI');setStatus(`${chart.length} AI notes · CACHED STEM: ${selected} · ${difficulty} · ${laneCount} lanes`)};
 const analyzeAll=async(file:File)=>{stop();setAnalyzing(true);setStemCache(null);setStatus('AI analysis: Demucs is separating and analyzing all 4 instruments…');if(urlRef.current)URL.revokeObjectURL(urlRef.current);const url=URL.createObjectURL(file);urlRef.current=url;setAudioUrl(url);setSongName(file.name);fileRef.current=file;try{const form=new FormData();form.append('file',file);const apiBase=(window.location.hostname==='localhost'||window.location.hostname==='127.0.0.1')?'http://127.0.0.1:8000':'/api/backend';const res=await fetch(`${apiBase}/analyze-all`,{method:'POST',body:form});if(!res.ok)throw new Error(await res.text());const data=await res.json();const cache:StemCache={Vocals:data.charts.vocals.notes,Drums:data.charts.drums.notes,Bass:data.charts.bass.notes,Melody:data.charts.melody.notes};setStemCache(cache);setDuration(data.duration);loadCachedStem(instrument,cache);setStatus(`Analysis complete · all 4 stems cached · ${instrument} ready · ${Number(data.duration).toFixed(1)}s`);ding()}catch(err){setStatus('AI analysis failed. Using the stable local generator for this song.');setBackendMode('LOCAL');try{const arr=await file.arrayBuffer();const ctx=new AudioContext();const buffer=await ctx.decodeAudioData(arr.slice(0));const generated=analyze(buffer);setBaseNotes(generated);setDuration(buffer.duration);setNotes(buildChart(generated,laneCount,difficulty));await ctx.close()}catch{setStatus('Song loaded, but analysis failed.');setNotes(demo)}}finally{setAnalyzing(false)}};
 const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;await analyzeAll(file)};
 const chooseInstrument=(x:Instrument)=>{if(x===instrument)return;setInstrument(x);if(stemCache){const generated=stemCache[x];setBaseNotes(generated);const chart=buildChart(generated,laneCount,difficulty);setNotes(chart);setBackendMode('AI');setStatus(`${chart.length} AI notes · CACHED STEM: ${x} · ${difficulty} · ${laneCount} lanes`)}};
 useEffect(()=>{if(audio.current)audio.current.volume=volume},[volume,audioUrl]);
 useEffect(()=>()=>{if(urlRef.current)URL.revokeObjectURL(urlRef.current)},[]);
 const travel=3.0;
 const upcoming=notes.filter(n=>!n.hit&&!n.miss&&n.time>=time&&n.time<=time+travel).length;
 const judged=hitStats.perfect+hitStats.great+hitStats.good+hitStats.miss;
 const accuracy=judged?((hitStats.perfect+hitStats.great*.8+hitStats.good*.5)/judged*100):0;
 const avgTimingMs=hitStats.timingHits?(hitStats.timingSum/hitStats.timingHits*1000):0;
 const timingLabel=Math.abs(avgTimingMs)<1?'ON TIME':avgTimingMs<0?'EARLY':'LATE';
 const songDuration=audioUrl?duration:34;
 const remaining=Math.max(0,songDuration-time);
 const multiplier=comboMultiplier(combo);
 const performancePoints=hitStats.perfect+hitStats.great*.8+hitStats.good*.5;
 const chartProgress=songDuration>0?Math.max(0,Math.min(1,time/songDuration)):0;
 const performanceQuality=judged?performancePoints/judged:0;
 const starProgress=Math.max(0,Math.min(5,chartProgress*performanceQuality*5));
 const progress=songDuration?Math.min(1,time/songDuration):0;
 const fmt=(secs:number)=>{const s=Math.max(0,Math.ceil(secs));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
 return <main><header><div><h1>BEAT<span>FORGE</span></h1><p>5 lane browser rhythm game</p></div></header>
 <section className="upload"><label className="uploadBtn">UPLOAD SONG<input type="file" accept="audio/*,.mp3,.wav,.ogg,.m4a" onChange={upload}/></label><div><strong>{songName}</strong><small>{analyzing?'Analyzing…':status}</small></div></section>
 <section className="chartOptions"><div><small>INSTRUMENT</small><div className="seg">{(['Vocals','Drums','Bass','Melody'] as Instrument[]).map(x=><button key={x} className={instrument===x?'active':''} disabled={analyzing} onClick={()=>chooseInstrument(x)}>{x}</button>)}</div></div><div><small>LANES</small><div className="seg">{[3,4,5].map(x=><button key={x} className={laneCount===x?'active':''} onClick={()=>setLaneCount(x)}>{x}</button>)}</div></div><div><small>DIFFICULTY</small><div className="seg">{(['Easy','Medium','Hard','Expert'] as Difficulty[]).map(x=><button key={x} className={difficulty===x?'active':''} onClick={()=>setDifficulty(x)}>{x}</button>)}</div></div><p className="analysisNote">{backendMode==='AI'?'AI generator active: Demucs stem separation + adaptive onset/hold detection.':'Local fallback generator active. Start the Python backend for AI charts.'}</p></section>
 {audioUrl&&<audio ref={audio} src={audioUrl} preload="auto"/>}
 <section className={`game ${multiplier===5?'goldMode':''}`}><div className="gameHud"><div className="hudScore"><b>{score.toLocaleString()}</b><small>SCORE</small></div><div className="hudCombo"><b>{combo} COMBO</b><strong>×{multiplier}</strong></div><div className="starMeter"><div className="stars">{[1,2,3,4,5].map(x=><span key={x} className={starProgress>=x?'earned':starProgress>=x-.8?'active':''}>★</span>)}</div><div className="starRail"><i style={{width:`${starProgress/5*100}%`}}/></div></div></div><div className={`judge ${judge.toLowerCase()}`}>{judge}</div><div className="lanes" style={{gridTemplateColumns:`repeat(${laneCount},1fr)`}}>{keys.map((k,l)=><div className={`lane ${pressed===l?'pressed':''}`} key={l}>{notes.filter(n=>n.lane===l&&!n.miss&&(!n.completed)).map(n=>{const dur=n.duration||0;const end=n.time+dur;const remaining=n.time-time;if(end<time-.20||remaining>travel)return null;const p=1-(remaining/travel);const endP=1-((end-time)/travel);const hold=dur>=.45;const top=Math.min(p,endP)*88;const height=Math.max(18,Math.abs(p-endP)*.88*610);return hold?<div key={n.id} className={`holdNote ${n.holding?'holding':''}`} style={{top:`${top}%`,height:`${height}px`}}><div className="holdHead"/></div>:<div key={n.id} className="note" style={{top:`calc(${p*88}% - 0px)`}}/>})}<div className={`receptor ${pressed===l?'filled':''}`}/>{impact?.lane===l&&<div key={impact.id} className={`impact ${impact.kind.toLowerCase()}`}/>}<div className={`key ${pressed===l?'keyPressed':''}`}>{k.toUpperCase()}</div></div>)}</div><div className="songProgress" aria-label={`Song progress, ${fmt(remaining)} remaining`}><span ref={remainingLabel} className="remainingLabel">{fmt(remaining)}</span><div className="progressRail"><div ref={progressFill} className="progressFill" style={{height:`${progress*100}%`}}/><div ref={progressKnob} className="progressKnob" style={{bottom:`calc(${progress*100}% - 8px)`}}/></div><small>LEFT</small></div></section>
 <section className="controls"><span className="debug">{running?`${upcoming} upcoming notes`:`${notes.length} notes ready`}</span><button disabled={analyzing} onClick={running?stop:play}>{running?'STOP':analyzing?'ANALYZING…':'PLAY'}</button><button className="secondary" onClick={stop}>RESET</button><label className="volume"><span>VOLUME</span><input aria-label="Volume" type="range" min="0" max="1" step="0.01" value={volume} onChange={e=>{const v=Number(e.target.value);setVolume(v);if(audio.current)audio.current.volume=v}}/><b>{Math.round(volume*100)}%</b></label><div className="time">{fmt(time)} / {fmt(songDuration)}</div></section>
 <section className="settings"><h2>Keybinds</h2><p>Click a box, then press the key you want for that lane.</p><div className="binds">{keys.map((k,i)=><button key={i} onKeyDown={e=>{e.preventDefault();setKeys(a=>a.map((x,j)=>j===i?e.key.toLowerCase():x))}}>{i+1}<strong>{k.toUpperCase()}</strong></button>)}</div></section>{resultsOpen&&<div className="resultBackdrop" role="dialog" aria-modal="true"><div className="resultCard"><small>SONG COMPLETE</small><h2>{songName}</h2><div className="finalScore">{score.toLocaleString()}</div><span className="scoreLabel">FINAL SCORE</span><div className="resultGrid"><div className="perfectStat"><b>{hitStats.perfect}</b><span>PERFECT</span></div><div className="goodStat"><b>{hitStats.good}</b><span>GOOD</span></div><div className="greatStat"><b>{hitStats.great}</b><span>GREAT</span></div><div className="missStat"><b>{hitStats.miss}</b><span>MISS</span></div></div><div className="resultMeta"><div><b>{accuracy.toFixed(1)}%</b><span>ACCURACY</span></div><div><b>{hitStats.maxCombo}×</b><span>MAX COMBO</span></div><div><b>{Math.abs(avgTimingMs).toFixed(0)} ms</b><span>{timingLabel}</span></div></div><div className="resultActions"><button onClick={()=>{setResultsOpen(false);play()}}>PLAY AGAIN</button><button className="secondary" onClick={()=>setResultsOpen(false)}>CLOSE</button></div></div></div>}<footer>BeatForge v0.13 · Vercel-ready + ×5 Gold Mode</footer></main>
}
