'use client';
import {useEffect,useRef} from 'react';
import {supabase} from '../lib/supabase';

type Match={id:string;player_1:string;player_2:string;status:string;candidate_chart_ids:string[];selected_chart_id:string|null;voting_ends_at:string|null;player_1_mmr_before:number;player_2_mmr_before:number};
type Chart={id:string;title:string;artist:string|null;youtube_url:string|null;play_count:number|null};

export default function RankedMultiplayer(){
 const overlay=useRef<HTMLDivElement|null>(null),poll=useRef<number|null>(null),matchId=useRef<string|null>(null);
 useEffect(()=>{
  if(!supabase)return;const db=supabase;
  const clearPoll=()=>{if(poll.current){window.clearInterval(poll.current);poll.current=null}};
  const portal=()=>document.fullscreenElement?.classList?.contains('beatforgeFullscreenShell')?document.fullscreenElement:document.body;
  const close=()=>{clearPoll();overlay.current?.remove();overlay.current=null};
  const modal=(html:string)=>{overlay.current?.remove();const o=document.createElement('div');o.className='rankedBackdrop realRanked';o.innerHTML='<div class="rankedCard">'+html+'</div>';portal().appendChild(o);overlay.current=o;return o.querySelector('.rankedCard') as HTMLElement};
  const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,(c:string)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
  const me=async()=>{const {data}=await db.auth.getUser();return data.user};
  const getPlayer=async(id:string)=>{const [{data:p},{data:r}]=await Promise.all([db.from('profiles').select('username').eq('id',id).maybeSingle(),db.from('ranked_players').select('mmr,wins,losses').eq('user_id',id).maybeSingle()]);return{username:p?.username||'Player',mmr:r?.mmr??1000,wins:r?.wins??0,losses:r?.losses??0}};
  const rank=(mmr:number)=>mmr<800?'BRONZE':mmr<1000?'SILVER':mmr<1200?'GOLD':mmr<1400?'PLATINUM':mmr<1600?'DIAMOND':'MASTER';
  const findMyMatch=async(uid:string)=>{const {data}=await db.from('ranked_matches').select('*').or(`player_1.eq.${uid},player_2.eq.${uid}`).in('status',['voting','ready','playing']).order('created_at',{ascending:false}).limit(1).maybeSingle();return data as Match|null};

  const waitForSharedStart=async(id:string)=>{
   clearPoll();let offset=0,started=false;
   const card=modal('<small>RANKED DUEL</small><h2>GET READY</h2><div class="syncCountdown">WAITING FOR OPPONENT</div><p class="syncHint">The song will start automatically when both players are ready.</p>');
   const label=card.querySelector('.syncCountdown') as HTMLElement;
   const check=async()=>{
    const t0=Date.now();const {data,error}=await db.rpc('get_ranked_start',{p_match:id});const t1=Date.now();
    if(error){label.textContent='SYNC ERROR';return}
    const row=Array.isArray(data)?data[0]:data;if(!row)return;
    const serverMs=new Date(row.server_now).getTime();offset=serverMs-((t0+t1)/2);
    if(!row.start_at){label.textContent=row.player_1_ready||row.player_2_ready?'1 / 2 READY':'WAITING FOR OPPONENT';return}
    const target=new Date(row.start_at).getTime();const left=target-(Date.now()+offset);
    label.textContent=left>3000?'4':left>2000?'3':left>1000?'2':left>0?'1':'GO!';
    if(left<=0&&!started){started=true;clearPoll();close();const play=[...document.querySelectorAll('button')].find(b=>b.textContent?.trim()==='PLAY') as HTMLButtonElement|undefined;play?.click()}
   };
   await check();poll.current=window.setInterval(check,120);
  };

  const armReady=async(id:string)=>{
   const card=modal('<small>RANKED DUEL</small><h2>SONG LOADED</h2><p>Press ready when you are set. Both players will receive the same synchronized countdown.</p><button class="rankedPrimary syncReady">READY</button><button class="rankedSecondary syncLeave">LEAVE</button>');
   (card.querySelector('.syncReady') as HTMLButtonElement).onclick=async()=>{const b=card.querySelector('.syncReady') as HTMLButtonElement;b.disabled=true;b.textContent='READY ✓';const {error}=await db.rpc('ready_ranked_match',{p_match:id});if(error){b.disabled=false;b.textContent='READY';modal('<small>RANKED ERROR</small><h2>READY FAILED</h2><p>'+esc(error.message)+'</p><button class="rankedSecondary closeRankError">CLOSE</button>').querySelector('.closeRankError')?.addEventListener('click',close);return}waitForSharedStart(id)};
   (card.querySelector('.syncLeave') as HTMLButtonElement).onclick=close;
  };

  const loadSelectedChart=async(chartId:string,id:string)=>{
   const {data:selected}=await db.from('charts').select('id,title,artist').eq('id',chartId).single();
   if(!selected){modal('<small>RANKED ERROR</small><h2>SONG NOT FOUND</h2><button class="rankedSecondary closeRankError">CLOSE</button>').querySelector('.closeRankError')?.addEventListener('click',close);return}
   close();const community=[...document.querySelectorAll('button')].find(b=>b.textContent?.trim()==='COMMUNITY') as HTMLButtonElement|undefined;community?.click();
   let tries=0;const timer=window.setInterval(()=>{tries++;const cards=[...document.querySelectorAll('.communityTile')] as HTMLElement[];const title=String(selected.title||'').trim().toLowerCase(),artist=String(selected.artist||'').trim().toLowerCase();const target=cards.find(c=>{const strong=c.querySelector('.tileInfo strong')?.textContent?.trim().toLowerCase()||'';const span=c.querySelector('.tileInfo span')?.textContent?.trim().toLowerCase()||'';return strong===title&&(!artist||span===artist)});if(target){window.clearInterval(timer);target.click();window.setTimeout(()=>armReady(id),500)}else if(tries>30){window.clearInterval(timer);modal('<small>RANKED ERROR</small><h2>COULD NOT LOAD SELECTED SONG</h2><p>The selected community chart could not be opened.</p><button class="rankedSecondary closeRankError">CLOSE</button>').querySelector('.closeRankError')?.addEventListener('click',close)}},150);
  };
  const showReady=async(chartId:string,id:string)=>{matchId.current=id;const {data:ch}=await db.from('charts').select('id,title,artist').eq('id',chartId).single();const card=modal('<small>RANKED DUEL</small><h2>SONG SELECTED</h2><div class="rankVoteWinner"><b>'+esc(ch?.title||'Selected chart')+'</b><span>'+esc(ch?.artist||'')+'</span></div><p>Both players received the same chart.</p><button class="rankedPrimary rankedLoad">LOAD SONG</button><button class="rankedSecondary rankedLeave">LEAVE</button>');(card.querySelector('.rankedLoad') as HTMLButtonElement).onclick=()=>loadSelectedChart(chartId,id);(card.querySelector('.rankedLeave') as HTMLButtonElement).onclick=close};
  const resolve=async(id:string)=>{const {data}=await db.rpc('resolve_ranked_vote',{p_match:id});if(data)showReady(data as string,id)};
  const voteScreen=async(m:Match)=>{clearPoll();matchId.current=m.id;const user=await me();if(!user)return;const oppId=m.player_1===user.id?m.player_2:m.player_1;const [opp,self,{data:charts},{data:votes}]=await Promise.all([getPlayer(oppId),getPlayer(user.id),db.from('charts').select('id,title,artist,youtube_url,play_count').in('id',m.candidate_chart_ids),db.from('ranked_votes').select('user_id,chart_id').eq('match_id',m.id)]);const list=(charts||[]) as Chart[];const remaining=Math.max(0,Math.ceil((new Date(m.voting_ends_at||Date.now()).getTime()-Date.now())/1000));const card=modal('<small>MATCH FOUND</small><h2>'+esc(self.username)+' <i class="voteVs">VS</i> '+esc(opp.username)+'</h2><p class="rankedVoteSub">Vote for the song · '+remaining+'s</p><div class="rankVoteGrid">'+list.map(ch=>'<button class="rankVote" data-id="'+ch.id+'">'+(ch.youtube_url?'<img src="https://i.ytimg.com/vi/'+((ch.youtube_url.match(/[?&]v=([^&]+)/)||ch.youtube_url.match(/youtu\.be\/([^?]+)/)||[])[1]||'')+'/mqdefault.jpg" alt="">':'')+'<strong>'+esc(ch.title)+'</strong><span>'+esc(ch.artist||'Unknown artist')+'</span><small>▶ '+Number(ch.play_count||0).toLocaleString()+'</small></button>').join('')+'</div><div class="rankedVoteStatus">'+(votes?.length||0)+'/2 VOTES LOCKED</div><button class="rankedSecondary cancelRealMatch">LEAVE</button>');card.querySelectorAll('.rankVote').forEach(b=>b.addEventListener('click',async()=>{card.querySelectorAll('.rankVote').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');await db.rpc('vote_ranked_chart',{p_match:m.id,p_chart:(b as HTMLElement).dataset.id});await resolve(m.id)}));(card.querySelector('.cancelRealMatch') as HTMLButtonElement).onclick=close;poll.current=window.setInterval(async()=>{const {data:mm}=await db.from('ranked_matches').select('*').eq('id',m.id).single();if(mm?.selected_chart_id){clearPoll();showReady(mm.selected_chart_id,m.id);return}const {count}=await db.from('ranked_votes').select('*',{count:'exact',head:true}).eq('match_id',m.id);const status=card.querySelector('.rankedVoteStatus');if(status)status.textContent=(count||0)+'/2 VOTES LOCKED';if((count||0)>=2||Date.now()>=new Date(m.voting_ends_at||0).getTime())await resolve(m.id)},700)};
  const search=async()=>{const user=await me();if(!user){const login=[...document.querySelectorAll('button')].find(b=>b.textContent?.trim()==='LOGIN') as HTMLButtonElement|undefined;close();login?.click();return}const self=await getPlayer(user.id);const card=modal('<small>RANKED DUEL</small><div class="queueSpinner"></div><h2>SEARCHING FOR REAL PLAYER</h2><p>Searching near '+self.mmr+' MMR…</p><small class="realQueueNote">You will both vote between 3 random charts from the Top 50 Trending.</small><button class="rankedSecondary cancelRealQueue">CANCEL</button>');(card.querySelector('.cancelRealQueue') as HTMLButtonElement).onclick=async()=>{await db.rpc('leave_ranked_queue');lobby()};const {data,error}=await db.rpc('join_ranked_queue');if(error){modal('<small>RANKED ERROR</small><h2>COULD NOT JOIN QUEUE</h2><p>'+esc(error.message)+'</p><button class="rankedSecondary closeRankError">CLOSE</button>').querySelector('.closeRankError')?.addEventListener('click',close);return}if(data){const {data:m}=await db.from('ranked_matches').select('*').eq('id',data).single();if(m){voteScreen(m);return}}clearPoll();poll.current=window.setInterval(async()=>{const m=await findMyMatch(user.id);if(m){clearPoll();voteScreen(m)}},800)};
  const lobby=async()=>{const user=await me();if(!user){search();return}const p=await getPlayer(user.id);const card=modal('<button class="rankedX">×</button><small>BEATFORGE COMPETITIVE</small><h1>RANKED DUEL</h1><div class="rankBadge"><b>'+rank(p.mmr)+'</b><strong>'+p.mmr+' MMR</strong><span>'+p.wins+'W · '+p.losses+'L</span></div><p>Real player matchmaking · one shared song · highest score wins.</p><div class="rankedFlow">MATCH → 3 SONGS → VOTE → READY → PLAY</div><button class="rankedPrimary realFindMatch">FIND MATCH</button>');(card.querySelector('.rankedX') as HTMLButtonElement).onclick=close;(card.querySelector('.realFindMatch') as HTMLButtonElement).onclick=search};
  const intercept=(e:Event)=>{const t=e.target as HTMLElement|null;const b=t?.closest?.('.rankedNavBtn');if(!b)return;e.preventDefault();e.stopPropagation();(e as any).stopImmediatePropagation?.();lobby()};document.addEventListener('click',intercept,true);return()=>{document.removeEventListener('click',intercept,true);close()};
 },[]);
 return <style>{`.rankedFlow{margin:14px auto;color:#a990ff;font-size:10px;font-weight:900;letter-spacing:.12em}.realQueueNote{display:block;color:#7f8798!important;margin:12px 0}.rankVoteGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:18px 0}.rankVote{padding:0!important;overflow:hidden;border:1px solid #303646!important;background:#0d1119!important;border-radius:13px!important;text-align:left!important;display:flex!important;flex-direction:column!important}.rankVote img{width:100%;height:92px;object-fit:cover}.rankVote strong{padding:10px 10px 2px;font-size:12px}.rankVote span,.rankVote small{padding:0 10px 7px;color:#8f98aa;font-size:9px}.rankVote.selected{border-color:#9b7cff!important;box-shadow:0 0 22px #7657ff55!important;transform:translateY(-2px)}.rankedVoteStatus{font-size:9px;color:#9ea6b7;font-weight:900;letter-spacing:.12em}.rankedVoteSub{margin:5px!important}.voteVs{font-style:normal;color:#7d8495;margin:0 8px}.rankVoteWinner{margin:18px auto;padding:18px;border:1px solid #493c78;background:#151126;border-radius:14px;display:grid;gap:5px}.rankVoteWinner b{font-size:20px}.rankVoteWinner span{color:#9da5b5}.syncCountdown{font-size:42px;font-weight:1000;color:#ffd43b;margin:22px 0;text-shadow:0 0 24px #ffd43b55}.syncHint{color:#9da5b5!important}.syncReady:disabled{opacity:.8}@media(max-width:700px){.rankVoteGrid{grid-template-columns:1fr}.rankVote img{height:75px}}`}</style>;
}
